apiVersion: v1
kind: Service
metadata:
  name: adminer-nodeport
  namespace: cluster-fastfood
spec:
  type: NodePort
  selector:
    app: adminer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000 