apiVersion: v1
kind: Service
metadata:
  name: app-nodeport
  namespace: cluster-fastfood
spec:
  type: NodePort
  selector:
    app: app
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30001 