apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  # namespace: cluster-fastfood
spec:
  serviceName: "mysql"
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        envFrom:
        - secretRef: 
            name: secret
        - configMapRef:
            name: mysql-config
        volumeMounts: 
        - name: mysql-storage
          mountPath: /var/lib/mysql
        resources:  
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:  
        - containerPort: 3306
        livenessProbe:  
          exec:
            command: ["/usr/bin/mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
          initialDelaySeconds: 60
          periodSeconds: 10
  volumeClaimTemplates:
  - metadata:
      name: mysql-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi